#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#阿里云 OSS
#不同的服务器，地址不同
OSS:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: ***********
  accessKeySecret: **********
  bucketName: edu-pengyuyan
